version: "3.3"

services:
  sails-api-template:
    container_name: sails-api-template
    build: ./server/
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "1337:1337"
    restart: always